name: Postgres
description: PostgreSQL is an object-relational database management system (ORDBMS) with an emphasis on extensibility and standards-compliance.
categories:
  - Database
labels:
  - database
  - open source
type: local
default_service_version: 9.4