name: CNAP Console
description: The CNAP Console provides the web interface for building and managing application in CNAP.
categories:
  - Console
labels:
  - UserInterface
type: by-ref
default_service_version: 1.0.0
