name: Haven On Demand
description: Haven On Demand is a collection of APIs for rapid development, high performance, and massive scalability.
categories:
  - Image Analysis
  - Indexing and Search
  - Format Conversion
  - Data Policy
  - Prediction
  - Audio/Video Analytics
  - Connectors
  - Search
labels:
  - RestApi
type: by-ref
default_service_version: 1.0
